In [1]:
import torch

## 基本介绍

- 复杂的接口，一些抽象的接口的深入理解
    - 理解复杂的代码；
    - 有助于构建复杂的神经网络，且清晰，不出错；
    
- 基于 index 在 原始 tensor 上选择（select）
    - 行选多个（行选1个是一种特例），提供的是列值(`dim=1`)；
        - 多个时，是几个必须一致；
    - 列选多个（列选1个是一种特例），提供的是行值（`dim=0`）；

- 要求，
    - input tensor 与 index 的 dim 相同
    - index.shape < input.shape

- 应用场景
    - batch sample 多分类问题的分类输出，获得各个true label 上的 score(logits)/probs（行选1个）
        - batch sample: n*c
        - index(true label): n*1
    - dqn：batch state 的 batch action 的输出，回归问题；
        ```
        state_action_values = policy_net(state_batch).gather(1, action_batch)
        ```
        - state_batch: n*d
        - action_batch: n*1
        - state_action_values: n*1

## 官网示例

In [16]:
t = torch.tensor([[1, 2], 
                  [3, 4]])
t

tensor([[1, 2],
        [3, 4]])

In [17]:
torch.gather(t, 1, torch.tensor([[0, 0], 
                                 [1, 0]]))

tensor([[1, 1],
        [4, 3]])

[0, 0]\
[1, 0] => 
> [(0, 0), (0, 0)]\
> [(1, 1), (1, 0)]

## 复杂例子

In [18]:
t = torch.arange(1, 10).view(3, 3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

- 如果想选择 (1,3), (5, 6)
    - 0, 2
    - 1, 2

In [19]:
t.gather(1, torch.tensor(((0, 2), (1, 2))))

tensor([[1, 3],
        [5, 6]])

- 如果想选择 (1, 4), (2, 8)，提供的是行值
    - (0, 1), 
    - (0, 2)

In [20]:
t.gather(0, torch.tensor(((0, 0), (1, 2))))

tensor([[1, 2],
        [4, 8]])